Spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace